repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.3
    hooks:
      - id: ruff
        entry: ruff check ./ruff_check/ --force-exclude --fix

        #args: [ ./ruff_check/*.py --fix ]

      - id: ruff-format
        entry: ruff format ./ruff_check/ --force-exclude

        #args: [ ./ruff_check/*.py --diff ]


