repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.3
    hooks:
      - id: ruff
        args: [.\ruff_check\main.py --fix]
      - id: ruff-format
        args: [./ruff_check/ --fix]


