repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.3
    hooks:
      - id: ruff
        entry: 'ruff check ruff_check/ --fix'
      - id: ruff-format
        args: ['ruff_check/main.py']


