- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.6.3
  hooks:
    # Run the linter.
    - id: ruff
      args: [ruff_check/*.py --fix]
    # Run the formatter.
    - id: ruff-format
      args: [ruff_check/*.py]