repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.3
    hooks:
      - id: ruff
        files: ./ruff_check/
        args: [--fix]
      - id: ruff-format
        files: ./ruff_check/
        args: [--diff]


